apiVersion: v1
kind: Service
metadata:
  name: secure-upload-server-service
spec:
  selector:
    app: secure-upload-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
